title: Lista #博客标题
description:  #博客描述
keywords: free #博客关键字
author: "Lista"

#title hide and show
hide: 
show: 

hosturl: "https://www.lista.cc" #for build static resource for main web.
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://www.lista.cc" # change this to the base hostname & protocol for your site
buildtime: "1514736000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: false #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
#paginate_path: "en/page:num"

background: /assets/image/head.jpeg
theme_color: 0078d4

google_analytics: UA-112881065-1
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji
  - jekyll-paginate

# social account
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
